export function createDashboardPage(runtime) {
  const { Button, EmptyState, Icon, PageHeader, ProgressBar, RoundCard, StationSelect, StationSummary, StatusBadge, formatDate, formatDateTime, getItemsForSnapshot, getRoundSummary, getStationReadiness, getVehicleReviewScopeEntries, getVehicleReviewState, getVehicleSearchReviewSummary, isVehicleReviewScopeState, profileFor, shortId } = runtime;
  return function DashboardPage({ state, update }) {
    const activeProfiles = state.stationProfiles.filter((entry) => entry.active !== false);
    const selectedId = activeProfiles.some((entry) => entry.id === state.ui?.selectedStationId)
      ? state.ui.selectedStationId
      : activeProfiles.some((entry) => entry.id === state.activeStationId)
        ? state.activeStationId
        : activeProfiles[0]?.id;
    const profile = selectedId ? profileFor(state, selectedId) : null;
    const profileReady = Boolean(profile && getStationReadiness(profile).ready && profile.readinessConfirmedAt);
    const rounds = state.inspectionRounds.filter((round) => round.stationId === profile?.id).sort((a, b) => new Date(b.updatedAt) - new Date(a.updatedAt));
    const latest = rounds.find(round => round.status !== "closed") || rounds[0];
    const summary = latest ? getRoundSummary(latest) : { total: 0, done: 0, issues: 0, pending: 0, progress: 0 };
    const vehicleSummary = latest ? getVehicleSearchReviewSummary(latest.vehicleSearch, { reviewVersion: latest.snapshot?.vehicleReviewVersion }) : { total: 0, reviewed: 0, pending: 0, accuracy: null, pendingChecks: 0, unableToVerifyChecks: 0, unresolvedChecks: 0, dimensions: { plate: { reviewed: 0, total: 0 }, classification: { reviewed: 0, total: 0 }, axles: { reviewed: 0, total: 0 }, integrity: { reviewed: 0, total: 0 } } };
    const vehicleScopeStatus = latest && isVehicleReviewScopeState(latest.vehicleSearch)
      ? getVehicleReviewScopeEntries(latest.vehicleSearch).map((scope) => `${scope.label} ${getVehicleReviewState(scope.state, { reviewVersion: latest.snapshot?.vehicleReviewVersion, context: "plate" }).summary.reviewed}/${scope.state.rows.length}`).join(" · ")
      : "";
    const issues = latest ? getItemsForSnapshot(latest.snapshot, latest.templateVersion || latest.snapshot?.templateVersion).filter((item) => ["damaged", "waiting"].includes(latest.inspectionItems[item.id]?.status)).slice(0, 5) : [];
    const setStation = (stationId) => update((current) => ({ ...current, activeStationId: stationId, ui: { ...(current.ui || {}), selectedStationId: stationId } }));
  
    return <section className="ops-page">
       <PageHeader eyebrow="WORKSPACE OVERVIEW" title="ภาพรวมการตรวจ" description="ดูความคืบหน้ารอบตรวจ และค้นหางานตามสัญญา งวด หรือสถานีได้" actions={<div className="ops-page-actions"><Button href={profile && profileReady ? "#/inspections/new" : profile ? `#/stations/${encodeURIComponent(profile.id)}` : "#/stations"} variant="primary" icon={profileReady ? "plus" : profile ? "settings" : "building"}>{profileReady ? "สร้างรอบตรวจ" : profile ? "ตั้งค่าความพร้อม" : "จัดการสถานี"}</Button><Button href="#/stations" icon="settings">ทะเบียนสถานี</Button></div>} />
      <section className="ops-panel ops-dashboard-station"><div className="ops-panel-toolbar"><StationSelect profiles={state.stationProfiles} value={profile?.id} onChange={setStation} /><a className="ops-text-link" href="#/stations">ดูทะเบียนอุปกรณ์ <Icon name="arrow" /></a></div><StationSummary profile={profile} /></section>
       {latest ? <><div className="ops-section-heading"><div><p className="ops-eyebrow">LATEST ROUND</p><h3>รอบการตรวจล่าสุด</h3></div><StatusBadge status={latest.status === "closed" ? "closed" : "draft"}>{latest.status === "closed" ? "ปิดรอบการตรวจแล้ว" : "อยู่ระหว่างกรอกข้อมูล"}</StatusBadge></div><section className="ops-panel ops-latest-round"><div><p className="ops-round-id">{profile?.stationCode} · รอบการตรวจ {shortId(latest.id)}</p><h3>{latest.meta.projectName || profile?.stationName}</h3><p>วันที่ตรวจ {latest.meta.inspectionDate ? formatDate(latest.meta.inspectionDate) : formatDate(latest.createdAt)} · อัปเดต {formatDateTime(latest.updatedAt)}</p></div><div className="ops-latest-progress"><strong>{summary.progress}%</strong><ProgressBar value={summary.progress} label={`${summary.done}/${summary.total} รายการ`} /></div><Button href={latest.status === "closed" ? `#/history/${encodeURIComponent(latest.id)}` : `#/inspections/${encodeURIComponent(latest.id)}`} variant="secondary" icon="arrow">{latest.status === "closed" ? "เปิดประวัติ" : "เปิดรายการตรวจ"}</Button></section><div className="combined-progress-summary"><span>ตรวจแล้ว <strong>{summary.done}/{summary.total} รายการ</strong></span><span>หลักฐานครบ <strong>{summary.evidenceComplete}/{summary.evidenceTotal} ช่อง</strong></span><span>รอตรวจ <strong>{summary.pending} รายการ</strong></span>{(latest.vehicleSearch?.fetchedAt || vehicleScopeStatus) && <span>Vehicle API <strong>{vehicleScopeStatus || `ป้าย ${vehicleSummary.dimensions.plate.reviewed}/${vehicleSummary.dimensions.plate.total}${vehicleSummary.dimensions.classification ? ` · ประเภท ${vehicleSummary.dimensions.classification.reviewed}/${vehicleSummary.dimensions.classification.total}` : ""}${vehicleSummary.dimensions.axles ? ` · เพลา ${vehicleSummary.dimensions.axles.reviewed}/${vehicleSummary.dimensions.axles.total}` : ""}${vehicleSummary.dimensions.integrity ? ` · น้ำหนัก ${vehicleSummary.dimensions.integrity.reviewed}/${vehicleSummary.dimensions.integrity.total}` : ""}`}</strong>{vehicleSummary.total ? ` · ค้าง ${vehicleSummary.unresolvedChecks} จุด` : " · ไม่พบรถ"}</span>}</div></> : <section className="ops-panel"><EmptyState icon="clipboard" title="ยังไม่มีรอบการตรวจของสถานีนี้" action={<Button href={profile && profileReady ? "#/inspections/new" : profile ? `#/stations/${encodeURIComponent(profile.id)}` : "#/stations"} variant="primary" icon={profileReady ? "plus" : profile ? "settings" : "building"}>{profileReady ? "เริ่มรอบตรวจแรก" : profile ? "ตั้งค่าความพร้อม" : "จัดการสถานี"}</Button>}>ตั้งค่าข้อมูลสถานีไว้แล้ว ขั้นตอนถัดไปคือเลือกสถานีและวันที่ตรวจ</EmptyState></section>}
      {rounds.filter(round=>round.status!=="closed" && round.id!==latest?.id).length>0 && <section className="ops-panel"><h3>รอบอื่นที่ต้องทำต่อ</h3>{rounds.filter(round=>round.status!=="closed" && round.id!==latest?.id).map(round=><RoundCard key={round.id} state={state} round={round}/>)}</section>}
      <section className="ops-panel ops-followup"><div className="ops-panel-heading"><div><p className="ops-eyebrow">FOLLOW-UP</p><h3>รายการที่ต้องติดตาม</h3></div>{latest && <a className="ops-text-link" href={`#/inspections/${encodeURIComponent(latest.id)}`}>ดูรอบการตรวจ <Icon name="arrow" /></a>}</div>{issues.length ? <div className="ops-followup-list">{issues.map((item) => <div className="ops-followup-row" key={item.id}><span className="ops-followup-icon"><Icon name="alert" /></span><div><strong>{item.label}</strong><span>{item.assetNo || item.location || "รายการหลัก"}</span></div><StatusBadge status={latest.inspectionItems[item.id]?.status} /></div>)}</div> : <EmptyState icon="check" title="ยังไม่มีรายการต้องติดตาม">เมื่อพบสถานะชำรุดหรืออยู่ระหว่างรอเปลี่ยนทดแทน รายการจะมาแสดงที่หน้านี้</EmptyState>}</section>
    </section>;
  }
}
