export function createHistoryPage(runtime) {
  const { Button, CustomSelect, EmptyState, Icon, PageHeader, RoundCard, getContractContextForRound, getCorrectionSummary, parseHash, profileFor, useDeferredValue, useState } = runtime;
  return function HistoryPage({ state, onDelete }) {
    const [query, setQuery] = useState("");
    const deferredQuery = useDeferredValue(query);
    const [stationFilter, setStationFilter] = useState(() => parseHash().query.stationId || "all");
    const [contractFilter, setContractFilter] = useState("all");
    const [workPackageFilter, setWorkPackageFilter] = useState("all");
    const packages = (state.workPackages || []).filter((entry) => contractFilter === "all" || entry.contractId === contractFilter);
    const rounds = state.inspectionRounds.filter((round) => round.status === "closed").filter((round) => { const profile = profileFor(state, round.stationId); const context = getContractContextForRound(round, state); const haystack = `${round.snapshot?.stationCode || ""} ${round.snapshot?.stationName || ""} ${profile?.stationCode || ""} ${profile?.stationName || ""} ${round.meta.projectName || ""} ${context?.contractNo || ""} ${context?.workPackageNo || ""} ${round.id} ${round.revisionReason || ""} ${getCorrectionSummary(round).latestReason || ""}`.toLowerCase(); return (!deferredQuery || haystack.includes(deferredQuery.toLowerCase())) && (stationFilter === "all" || round.stationId === stationFilter) && (contractFilter === "all" || context?.contractId === contractFilter) && (workPackageFilter === "all" || context?.workPackageId === workPackageFilter); }).sort((a, b) => new Date(b.closedAt || b.updatedAt) - new Date(a.closedAt || a.updatedAt));
    return <section className="ops-page"><PageHeader eyebrow="CLOSED INSPECTIONS" title="ประวัติและพิมพ์รายงาน" description="รอบการตรวจที่ปิดแล้วอ่านจาก Snapshot เดิม และกรองตามสัญญา → งวด → สถานีได้" actions={<Button href="#/inspections" icon="list">ดูรอบการตรวจที่กำลังกรอก</Button>} /><section className="ops-panel"><div className="ops-filter-bar"><label className="ops-search"><Icon name="search" /><span className="sr-only">ค้นหาประวัติ</span><input type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="ค้นหาเลขสัญญา งวด หรือสถานี..." /></label><label className="ops-field ops-filter-select"><span>สัญญา</span><CustomSelect value={contractFilter} onChange={(event) => { setContractFilter(event.target.value); setWorkPackageFilter("all"); }}><option value="all">ทุกสัญญา</option>{(state.contracts || []).map((entry) => <option key={entry.id} value={entry.id}>{entry.contractNo} · {entry.title}</option>)}</CustomSelect></label><label className="ops-field ops-filter-select"><span>งวด</span><CustomSelect value={workPackageFilter} disabled={contractFilter === "all"} onChange={(event) => setWorkPackageFilter(event.target.value)}><option value="all">ทุกงวด</option>{packages.map((entry) => <option key={entry.id} value={entry.id}>{entry.reportSequence || entry.packageNo} · {entry.title}</option>)}</CustomSelect></label><label className="ops-field ops-filter-select"><span>สถานี</span><CustomSelect value={stationFilter} onChange={(event) => setStationFilter(event.target.value)} aria-label="เลือกสถานีในประวัติ" label="เลือกสถานีในประวัติ"><option value="all">ทุกสถานี</option>{state.stationProfiles.map((profile) => <option key={profile.id} value={profile.id}>{profile.stationCode} · {profile.stationName}{profile.active === false ? " · ปิดใช้งาน" : ""}</option>)}</CustomSelect></label></div><div className="ops-round-list">{rounds.length ? rounds.map((round) => <RoundCard key={round.id} state={state} round={round} onDelete={onDelete} />) : <EmptyState icon="archive" title="ยังไม่มีประวัติที่ปิดแล้ว">ปิดรอบการตรวจจากหน้ารายการตรวจและหลักฐาน แล้วรายงานจะมาอยู่ที่นี่</EmptyState>}</div></section></section>;
  }
}
