export function createInspectionsPage(runtime) {
  const { Button, CustomSelect, EmptyState, Icon, PageHeader, RoundCard, getContractContextForRound, parseHash, profileFor, useDeferredValue, useState } = runtime;
  return function InspectionsPage({ state, onDelete }) {
    const [query, setQuery] = useState("");
    const deferredQuery = useDeferredValue(query);
    const [stationFilter, setStationFilter] = useState(() => parseHash().query.stationId || "all");
    const [contractFilter, setContractFilter] = useState("all");
    const [workPackageFilter, setWorkPackageFilter] = useState("all");
    const packages = (state.workPackages || []).filter((entry) => contractFilter === "all" || entry.contractId === contractFilter);
    const rounds = state.inspectionRounds.filter((round) => round.status !== "closed").filter((round) => { const profile = profileFor(state, round.stationId); const context = getContractContextForRound(round, state); const haystack = `${round.snapshot?.stationCode || ""} ${round.snapshot?.stationName || ""} ${profile?.stationCode || ""} ${profile?.stationName || ""} ${round.meta.projectName || ""} ${context?.contractNo || ""} ${context?.workPackageNo || ""} ${round.id}`.toLowerCase(); return (!deferredQuery || haystack.includes(deferredQuery.toLowerCase())) && (stationFilter === "all" || round.stationId === stationFilter) && (contractFilter === "all" || context?.contractId === contractFilter) && (workPackageFilter === "all" || context?.workPackageId === workPackageFilter); }).sort((a, b) => new Date(b.updatedAt) - new Date(a.updatedAt));
    return <section className="ops-page"><PageHeader eyebrow="INSPECTION WORKSPACE" title="รอบการตรวจที่กำลังกรอก" description="หน้านี้แสดงฉบับร่างที่ยังทำงานอยู่ และค้นหาหรือกรองตามสัญญา งวด และสถานีได้" actions={<Button href="#/inspections/new" variant="primary" icon="plus">สร้างรอบตรวจ</Button>} /><section className="ops-panel"><div className="ops-filter-bar"><label className="ops-search"><Icon name="search" /><span className="sr-only">ค้นหารอบการตรวจ</span><input type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="ค้นหาเลขสัญญา งวด รอบตรวจ หรือสถานี..." /></label><label className="ops-field ops-filter-select"><span>สัญญา</span><CustomSelect value={contractFilter} onChange={(event) => { setContractFilter(event.target.value); setWorkPackageFilter("all"); }}><option value="all">ทุกสัญญา</option>{(state.contracts || []).map((entry) => <option key={entry.id} value={entry.id}>{entry.contractNo} · {entry.title}</option>)}</CustomSelect></label><label className="ops-field ops-filter-select"><span>งวด</span><CustomSelect value={workPackageFilter} disabled={contractFilter === "all"} onChange={(event) => setWorkPackageFilter(event.target.value)}><option value="all">ทุกงวด</option>{packages.map((entry) => <option key={entry.id} value={entry.id}>{entry.reportSequence || entry.packageNo} · {entry.title}</option>)}</CustomSelect></label><label className="ops-field ops-filter-select"><span>สถานี</span><CustomSelect label="สถานี" value={stationFilter} onChange={(event) => setStationFilter(event.target.value)}><option value="all">ทุกสถานี</option>{state.stationProfiles.filter((profile) => profile.active !== false).map((profile) => <option key={profile.id} value={profile.id}>{profile.stationCode} · {profile.stationName}</option>)}</CustomSelect></label></div><div className="ops-round-list" aria-live="polite">{rounds.length ? rounds.map((round) => <RoundCard key={round.id} state={state} round={round} onDelete={onDelete} />) : <EmptyState icon="search" title="ยังไม่พบรอบที่กำลังกรอก">ลองเปลี่ยนตัวกรอง หรือสร้างรอบตรวจจากสถานีที่พร้อมใช้งาน</EmptyState>}</div></section></section>;
  }
}
