import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { readAppSource, readPageSource } from "./source-bundle.mjs";

const appSource = readAppSource();
const checklistSource = readPageSource("ChecklistPage.jsx");
const vehicleReviewSource = readPageSource("VehicleApiReviewPage.jsx");
const pageRuntimeSource = readFileSync(new URL("../src/app/page-runtime.js", import.meta.url), "utf8");
const redesignCss = readFileSync(new URL("../src/styles/redesign.css", import.meta.url), "utf8");
const workspaceCss = readFileSync(new URL("../src/styles/workspace-layout.css", import.meta.url), "utf8");
const envExample = readFileSync(new URL("../.env.example", import.meta.url), "utf8");
const singleViewportCss = redesignCss.slice(redesignCss.indexOf("/* Single-viewport inspection workspace"));
const shortVehicleFallback = workspaceCss.slice(workspaceCss.indexOf("@media screen and (max-width: 1279px), screen and (max-height: 760px)"));
const strictShortViewportCss = workspaceCss.slice(workspaceCss.indexOf("@media screen and (max-height: 560px) {"));

const openReviewBody = checklistSource.match(/const openVehicleApiReview = \(\) => \{([\s\S]*?)\n\s+\};/)?.[1] || "";
assert.doesNotMatch(openReviewBody, /window\.location\.hash\s*=/, "Vehicle API checklist CTA should stay in the current round URL");
assert.match(openReviewBody, /navigate\(vehicleApiHref\(visibleRound, currentVehicleContext\.key/, "Vehicle API checklist CTA should open the dedicated context page");

assert.match(checklistSource, /className=\{`ops-page checklist-page[^`]*\$\{currentIsVehicleReview \? "is-vehicle-review-entry"/, "vehicle Checklist items should use a compact entry layout");
assert.match(checklistSource, /ops-vehicle-review-entry/, "vehicle Checklist items should show a compact entry card instead of an inline review panel");
assert.match(checklistSource, /เปิดหน้าตรวจ/, "active vehicle Checklist items should offer a dedicated review page");
assert.match(checklistSource, /vehicleApiHref\(visibleRound, currentVehicleContext\?\.key, \{ history: formReadOnly \}\)/, "closed and history Checklist items should open the matching read-only context page");
assert.match(vehicleReviewSource, /const isDemoRoute = !storedRound && route\.name === "vehicleApi" && route\.id === UI_VEHICLE_DEMO_ROUND_ID/, "the dedicated Vehicle API route should recognize the non-persisted vehicle demo round");
assert.match(vehicleReviewSource, /useState\(\(\) => isDemoRoute \? createUiVehicleDemoRound\(\) : null\)/, "the dedicated Vehicle API demo route should provide its fixture without saving it as a real round");
assert.match(vehicleReviewSource, /isDemoRoute && <span className="ops-vehicle-demo-badge" role="status">ตัวอย่าง · ไม่บันทึกรอบจริง/, "the dedicated Vehicle API demo route should identify its non-persisted data in the compact header");
assert.match(pageRuntimeSource, /vehicleApi: Object\.freeze\(\[[\s\S]*?"UI_VEHICLE_DEMO_ROUND_ID"[\s\S]*?"createUiVehicleDemoRound"[\s\S]*?"useState"/, "the Vehicle API page runtime should expose the isolated demo route dependencies");
assert.match(appSource, /วาง URL เต็มของ Vehicle API/, "station setup should make full URL paste the primary Vehicle API flow");
assert.doesNotMatch(appSource, /61\.19\.97\.189|192\.168\.145\.90/, "the UI should not embed a real station or proxy IP in its example URL");
assert.doesNotMatch(envExample, /159\.192\.123\.229|61\.19\.97\.189|192\.168\.145\.90/, "the environment example should not embed a live station or proxy IP");
assert.match(appSource, /parseVehicleSearchUrl/, "station setup should parse pasted Vehicle API URLs through the domain seam");
assert.match(appSource, /วาง URL แล้วทดสอบ/, "Vehicle API should expose one combined paste-and-test action");
assert.doesNotMatch(appSource, /ตั้งค่าแบบแยก IP\/Port \(ขั้นสูง\)/, "manual IP and port fields should not remain in the simplified setup UI");
assert.doesNotMatch(appSource, /vehicle-api-station-id-/, "stationID should not remain as a manual input in the simplified setup UI");
assert.doesNotMatch(appSource, /current\.stationId && result\.sourceStation\?\.id/, "a stale stationID must not block a newly pasted URL test");
assert.match(appSource, /ops-vehicle-review-evidence/, "inline vehicle review should expose its checklist evidence area");
assert.match(appSource, /ops-vehicle-review-image-media/, "vehicle review images should isolate media from action text");
assert.match(appSource, /className=\"ops-vehicle-review-image-media\"/, "vehicle review image should render a dedicated media frame");
assert.match(appSource, /mediaFrame\?\.setAttribute\("hidden", ""\)/, "a failed vehicle image should hide only its media frame");
assert.match(appSource, /ops-vehicle-review-image-empty/, "a failed vehicle image should reveal its explicit empty state");
assert.match(checklistSource, /navigate\(query\.size \? `\$\{href\}\?\$\{query\.toString\(\)\}` : href\)/, "closing blockers should open the dedicated vehicle page with the selected row context");
assert.match(appSource, /const isApiOnlyReview = reviewVersion === VEHICLE_API_REVIEW_VERSION/, "v2 Vehicle API items should use the API-only evidence mode");
assert.match(appSource, /data-vehicle-evidence-mode=\{isApiOnlyReview \? "api" : "attachment"\}/, "Vehicle review should expose its evidence mode for regression checks");
assert.match(appSource, /isApiOnlyReview && <section className="ops-vehicle-api-proof"/, "API-only review should identify API data as the inspection evidence");
assert.match(appSource, /criteriaDirty \? "เปลี่ยนช่วงเวลาแล้ว · ต้องดึงข้อมูลใหม่" : reviewStatusLabel/, "the compact API status should not repeat the fetch timestamp already shown in provenance");
assert.match(appSource, /หลักฐานการตรวจจาก API/, "API-only review should explain what counts as evidence");
assert.match(appSource, /ช่วงเวลา \{formatThaiDateTimeInput\(searchState\.criteria\.startAt\)/, "API-only review should expose the fetched time range in the Thai project format");
assert.match(appSource, /ThaiDateTimePicker value=\{criteria\.startAt\}/, "Vehicle API time criteria should use the project custom picker");
assert.doesNotMatch(appSource, /type="datetime-local"/, "Vehicle API should not fall back to the browser-native datetime picker");
assert.match(appSource, /evidenceItem && !isApiOnlyReview && <section className="ops-vehicle-review-evidence"/, "manual evidence controls should remain available for legacy review items");
assert.match(appSource, /isVehicleCriteriaDirty\(criteria, searchState\.criteria\)/, "Vehicle API review should detect when the selected time range differs from the fetched result");
assert.match(appSource, /ระบบพักผลเดิมไว้จนกว่าจะกด “ดึงข้อมูลรถจาก API” ใหม่/, "a stale Vehicle API result should be held until the user fetches the new range");
assert.match(appSource, /getVehicleReviewUnresolvedUnit\(activeDimensions\)/, "vehicle review should choose count units from the active review context");
assert.match(appSource, /!isPlateContext && row\.axles\.length > 0/, "plate context should not render axle details in the legacy review card");
assert.match(appSource, /\(row\.integrityWarnings\?\.length \|\| row\.errorFlags\?\.length \|\| row\.warningFlags\?\.length\)/, "legacy vehicle review should retain integrity warning evidence");
assert.match(appSource, /ไปคันค้างถัดไป/, "pending navigation should explicitly target the next unresolved vehicle");
assert.doesNotMatch(appSource, /ops-vehicle-scope-tabs/, "day/night scope tabs should be removed from the focused review UI");
assert.match(appSource, /function VehicleReviewImage\(\{[^}]*loading = "lazy"/s, "vehicle review images should keep lazy loading by default");
assert.equal(appSource.includes('loading="eager"'), true, "the focused vehicle evidence image must load eagerly inside the scroll workspace");
assert.match(appSource, /ยืนยันว่าไม่มีรถช่วงนี้/, "an empty day/night API result must be explicitly acknowledged");
assert.match(appSource, /data-vehicle-scope=\{isScopedReview \? activeScopeKey : "all"\}/, "the active day/night scope should be exposed for QA and accessibility");
assert.match(redesignCss, /\.ops-vehicle-focus-row-list button em\.is-done \{ background: var\(--ops-success-soft\); color: var\(--ops-success\); \}/, "completed queue status should use readable foreground and background colors");

assert.match(redesignCss, /\.checklist-page:not\(\.is-report-previewing\)\.is-vehicle-review > \.ops-taskflow-layout\s*\{[\s\S]*grid-template-columns:\s*minmax\(260px,\s*280px\)\s+minmax\(0,\s*1fr\)/, "vehicle review should span the result area instead of reserving a blank drawer column");
assert.match(redesignCss, /\.checklist-page:not\(\.is-report-previewing\)\.is-vehicle-review > \.ops-taskflow-layout > \.ops-taskflow-main\s*\{[\s\S]*grid-column:\s*2\s*\/\s*-1/, "vehicle review should use the existing middle and right workspace columns");
assert.match(redesignCss, /\.ops-vehicle-review-evidence\s*\{/, "vehicle evidence should have a bounded panel style");
assert.match(redesignCss, /\.ops-vehicle-api-proof\s*\{/, "API-only review should have a read-only evidence summary style");
assert.match(redesignCss, /\.ops-vehicle-focus-image\s*\{[^}]*display:\s*flex[^}]*flex-direction:\s*column/s, "focused vehicle image should reserve a separate row for the action label");
assert.match(redesignCss, /\.ops-vehicle-focus-image \.ops-vehicle-review-image-media\s*\{[^}]*min-height:\s*0[^}]*overflow:\s*hidden/s, "focused vehicle image should clip only inside its dedicated media frame");
assert.match(redesignCss, /\.ops-vehicle-focus-image \.ops-vehicle-review-image-media img\s*\{[^}]*width:\s*auto[^}]*height:\s*auto[^}]*max-width:\s*100%[^}]*max-height:\s*100%[^}]*object-fit:\s*contain/s, "focused vehicle image should preserve the full source ratio without percentage-height overflow");
assert.match(redesignCss, /\.checklist-page\.is-vehicle-review \.ops-vehicle-focus-panel\s*\{[\s\S]*display:\s*flex[\s\S]*height:\s*100%/, "vehicle review panel should consume the available workspace height");
assert.match(redesignCss, /\.checklist-page\.is-vehicle-review > \.ops-taskflow-layout > \.ops-taskflow-main > \.ops-check-section-list\.is-vehicle-focus-list\s*\{[\s\S]*overflow:\s*hidden/, "vehicle review should remove the generic outer result scrollbar");
assert.match(redesignCss, /\.checklist-page\.is-vehicle-review \.ops-vehicle-focus-layout\s*\{[\s\S]*flex:\s*1 1 0[\s\S]*grid-template-rows:\s*minmax\(0,\s*1fr\)/, "vehicle review columns should fill the remaining height");
assert.match(redesignCss, /is-vehicle-focus-mode/, "vehicle review should support an optional full-width focus mode");
assert.match(redesignCss, /\.ops-vehicle-focus-row-list button \{ min-height: 56px; \}/, "vehicle queue rows should stay dense while preserving a large touch target");
assert.match(redesignCss, /\.ops-vehicle-review-actions button \{ min-height: 46px;/, "vehicle review decisions should keep a touch-safe target");
assert.match(shortVehicleFallback, /\.ops-vehicle-api-page\s*\{[^}]*overflow-y:\s*auto/s, "short-height fallback should give the dedicated Vehicle API page one vertical scroll owner");
assert.match(shortVehicleFallback, /\.ops-vehicle-api-page \.ops-vehicle-focus-layout\s*\{[^}]*grid-template-columns:\s*minmax\(180px,\s*\.55fr\)\s+minmax\(0,\s*1fr\)/s, "wide short-height Vehicle API pages should collapse to two columns");
assert.match(shortVehicleFallback, /\.ops-vehicle-api-page \.ops-vehicle-focus-(?:queue|main|inspector)[^}]*height:\s*auto[^}]*overflow:\s*visible/s, "dedicated Vehicle API columns should not own nested scrollbars at short heights");
assert.match(shortVehicleFallback, /\.ops-vehicle-focus-image\s*\{[^}]*aspect-ratio:\s*16\s*\/\s*9[^}]*min-height:\s*220px/s, "short-height vehicle image should keep a usable aspect ratio");
assert.match(singleViewportCss, /\.ops-main:has\(\.checklist-page:not\(\.is-report-previewing\)\)\s*\{(?=[^}]*display:\s*flex)[^}]*display:\s*flex[^}]*flex-direction:\s*column[^}]*\}/, "single-viewport checklist main should reserve height below the topbar");
assert.match(singleViewportCss, /\.checklist-page:not\(\.is-report-previewing\)\s*\{(?=[^}]*height:\s*auto)[^}]*height:\s*auto[^}]*flex:\s*1 1 0[^}]*\}/, "single-viewport checklist page should use remaining height instead of stacking below a full-height topbar");
assert.match(strictShortViewportCss, /\.checklist-page\.is-vehicle-decision-dock\s*\{[\s\S]*overflow:\s*hidden/s, "short focused review view should keep document scrolling disabled");
assert.match(strictShortViewportCss, /\.ops-vehicle-responsive-tabs\s*\{[\s\S]*display:\s*grid/s, "short focused review view should expose the single-panel tabs");
assert.match(strictShortViewportCss, /\.ops-vehicle-focus-layout > \[data-dock-panel\]\s*\{[\s\S]*display:\s*none/s, "short focused review view should hide inactive panels");
assert.match(strictShortViewportCss, /data-responsive-panel=\"queue\"[\s\S]*data-dock-panel=\"queue\"/s, "short focused review view should display the active queue panel");
assert.match(workspaceCss, /@media screen and \(max-width: 780px\) and \(min-height: 561px\)[\s\S]*grid-template-columns: minmax\(0, 1fr\)/s, "mobile criteria should stack into one column");
assert.match(strictShortViewportCss, /@media screen and \(max-height: 560px\) and \(max-width: 780px\)[\s\S]*grid-template-columns: repeat\(2, minmax\(0, 1fr\)\)/s, "short mobile criteria should use the compact two-column fallback");

console.log("vehicle inline workspace contract tests passed");
